baseURL = "https://konyahackerspace.org/"
title = "Konya Hackerspace"
languageCode = "en"
theme = "PaperMod"

# Nice URLs
[permalinks]
  blog = "/blog/:year/:month/:slug/"

# Menu
[menu]
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 10
  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 20

# PaperMod basics
[params]
  defaultTheme = "dark" 
  showReadingTime = false
  showShareButtons = false
  disableThemeToggle = true
