baseURL = "https://konyahackerspace.org/"
title = "Konya Hackerspace"
languageCode = "en"
theme = "terminal"
copyright = "Powered by Hugo"

# Nice URLs
[permalinks]
  blog = "/blog/:year/:month/:slug/"

# Menu
[menu]
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 20
  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 10

# PaperMod basics
[params]
  defaultTheme = "dark" 
  showReadingTime = false
  showShareButtons = false
  disableThemeToggle = true

  centerTheme = true
  dateFormat = "02-01-2006"
  logo.logoText = " "
  readMore = "More..."
