# .github/workflows/hugo.yml
name: Build and Deploy Hugo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Install Hugo (extended) — use latest or pin >= 0.146.0
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'   # or '0.149.0' etc.
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
